CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE;

CREATE TABLE IF NOT EXISTS USUARIO (
  id INT NOT NULL,
  username VARCHAR(45) NOT NULL,
  passwd VARCHAR(20) NOT NULL,
  nombre VARCHAR(30) NOT NULL,
  programa VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CUADERNILLO (
  id INT NOT NULL DEFAULT nextval('CUADERNILLOS_ID_SEQ'),
  administrador INT NOT NULL,
  nombre VARCHAR(45) UNIQUE NOT NULL,
  tablero VARCHAR2(10485760) NOT NULL,
  publico BOOLEAN NOT NULL,
  editable BOOLEAN NOT NULL,
  materia INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY(administrador) REFERENCES USUARIOS(id),
  FOREIGN KEY(materia) REFERENCES MATERIAS(id)
);

CREATE TABLE IF NOT EXISTS PARTICIPANTES (
  idUsuario INT NOT NULL,
  idCuadernillo INT NOT NULL,
  PRIMARY KEY (idUsuario,idCuadernillo)
);

CREATE TABLE IF NOT EXISTS MATERIAS (
  id INT NOT NULL,
  nombre VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);