CREATE SEQUENCE IF NOT EXISTS CUADERNILLOS_ID_SEQ;

CREATE TABLE IF NOT EXISTS USUARIOS (
  id INT NOT NULL,
  username VARCHAR(45) NOT NULL UNIQUE,
  passwd VARCHAR(20) NOT NULL,
  nombre VARCHAR(30) NOT NULL,
  programa VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS CUADERNILLOS (
  id INT NOT NULL DEFAULT nextval('CUADERNILLOS_ID_SEQ'),
  administrador INT NOT NULL UNIQUE,
  nombre VARCHAR(45) NOT NULL,
  tablero VARCHAR(45) NOT NULL,
  publico BOOLEAN NOT NULL,
  editable BOOLEAN NOT NULL,
  materia INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY(administrador) REFERENCES USUARIOS(id),
  FOREIGN KEY(materia) REFERENCES MATERIAS(id)
);

CREATE TABLE IF NOT EXISTS ROLES (
  id INT NOT NULL,
  nombre VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (id))
;